# Generated by Django 4.2.6 on 2024-08-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_of_rejected_votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
