# Generated by Django 4.2.6 on 2024-08-13 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0002_number_of_rejected_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Number_of_rejected_votes',
            new_name='Rejected_votes',
        ),
    ]
